# Generated by Django 3.2 on 2024-07-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20240702_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('DESC', 'Descriptive')], default='MCQ', max_length=4),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
