# Generated by Django 3.2 on 2024-07-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
