# Generated by Django 5.0.5 on 2024-07-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
